const fs = require('fs');

const content = `export type Lang = 'es' | 'en'

export const translations = {
  es: {
    nav: ['Advisory', 'Activos Mineros', 'Análisis de Mercado', 'Regiones', 'Leadership', 'Contacto'],
    heroEyebrow: 'Andes Mining Advisory',
    heroTitle1: 'Strategic',
    heroTitle2: 'Mining Advisory',
    heroText: 'Protegemos, desarrollamos y maximizamos el valor de activos mineros estratégicos en Chile, Argentina y Perú.',
    heroSubline: 'Concesiones Mineras • Due Diligence • Brokerage Minero • Market Analysis',
    ctaPrimary: 'Explorar advisory',
    ctaSecondary: 'Contactar',
    trust: [
      ['+200', 'Concesiones mineras tramitadas por año'],
      ['3', 'Países estratégicos: Chile, Argentina y Perú'],
      ['Legal · Técnico · Comercial', 'Criterio integrado para decisiones mineras'],
      ['NDA', 'Procesos bajo estricta confidencialidad'],
    ],
    whyEyebrow: 'Why AMA',
    whyTitle: 'Los activos mineros requieren decisiones estratégicas.',
    whyText: 'AMA ayuda a empresas mineras, inversionistas y titulares de concesiones a proteger, evaluar y desarrollar activos mineros con criterio legal, técnico y comercial.',
    aboutEyebrow: 'Activos Mineros',
    aboutTitle: 'No se trata solo de tramitar. Se trata de proteger valor.',
    aboutText: 'AMA Mining integra experiencia legal, técnica y comercial para apoyar decisiones críticas sobre concesiones, proyectos, oportunidades de inversión y activos mineros de alto valor.',
    servicesEyebrow: 'Advisory',
    servicesTitle: 'Áreas de advisory estratégico',
    servicesSubtitle: 'Acompañamos a propietarios de activos, inversionistas, compañías mineras y proveedores estratégicos en decisiones de alto impacto.',
    marketEyebrow: 'Market Analysis',
    marketTitle: 'Análisis de mercado para decisiones mineras',
    marketText: 'Seguimiento de metales, señales de mercado, regulación, riesgos concesionales y oportunidades de inversión en Chile, Argentina y Perú.',
    marketButton: 'Ver Market Analysis Center',
    regionsEyebrow: 'Regiones',
    regionsTitle: 'Chile, Argentina y Perú',
    teamEyebrow: 'Leadership',
    teamTitle: 'Liderazgo estratégico minero',
    contactEyebrow: 'Contacto',
    contactTitle: 'Hablemos de su activo minero',
    contactText: 'Trabajamos bajo confidencialidad, visión estratégica y foco en proteger y desarrollar oportunidades mineras de alto potencial.',
  },
  en: {
    nav: ['Advisory', 'Mining Assets', 'Market Analysis', 'Regions', 'Leadership', 'Contact'],
    heroEyebrow: 'Andes Mining Advisory',
    heroTitle1: 'Strategic',
    heroTitle2: 'Mining Advisory',
    heroText: 'Protecting, developing and maximizing the value of strategic mining assets across Chile, Argentina and Peru.',
    heroSubline: 'Mining Concessions • Due Diligence • Mining Brokerage • Market Analysis',
    ctaPrimary: 'Explore advisory',
    ctaSecondary: 'Contact',
    trust: [
      ['+200', 'Mining concessions processed every year'],
      ['3', 'Strategic countries: Chile, Argentina and Peru'],
      ['Legal · Technical · Commercial', 'Integrated criteria for mining decisions'],
      ['NDA', 'Processes under strict confidentiality'],
    ],
    whyEyebrow: 'Why AMA',
    whyTitle: 'Mining assets require strategic decisions.',
    whyText: 'AMA helps mining companies, investors and concession holders protect, evaluate and develop mining assets through legal, technical and commercial criteria.',
    aboutEyebrow: 'Mining Assets',
    aboutTitle: 'It is not just about processing. It is about protecting value.',
    aboutText: 'AMA Mining integrates legal, technical and commercial expertise to support critical decisions regarding concessions, projects, investment opportunities and high-value mining assets.',
    servicesEyebrow: 'Advisory',
    servicesTitle: 'Strategic advisory areas',
    servicesSubtitle: 'We advise asset owners, investors, mining companies and strategic suppliers on high-impact mining decisions.',
    marketEyebrow: 'Market Analysis',
    marketTitle: 'Market analysis for mining decisions',
    marketText: 'Monitoring metals, market signals, regulation, concession risks and investment opportunities across Chile, Argentina and Peru.',
    marketButton: 'View Market Analysis Center',
    regionsEyebrow: 'Regions',
    regionsTitle: 'Chile, Argentina and Peru',
    teamEyebrow: 'Leadership',
    teamTitle: 'Strategic mining leadership',
    contactEyebrow: 'Contact',
    contactTitle: 'Let’s discuss your mining asset',
    contactText: 'We operate with confidentiality, strategic vision and a strong focus on protecting and developing high-potential mining opportunities.',
  },
}
`;

fs.writeFileSync('app/lib/translations.ts', content, 'utf8');
console.log('translations.ts reparado en UTF-8');